# Generated by Django 4.1.2 on 2022-10-28 19:24

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
