# Generated by Django 4.1.2 on 2022-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '__first__'),
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='posts.post', verbose_name='Понравившиеся публикации'),
        ),
    ]
