# Generated by Django 4.1.2 on 2022-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужчина'), ('FEM', 'Женщина'), ('OTHER', 'Другой')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
